# This code builds the text for the Publication bias tab for meta.pipeline.shiny.R
         # Write trim-and-fill results
         tags$strong("Trim and fill"),
         tags$br(),
         "Number of detected missing studies:", results$trim.miss,
         tags$br(),
         "Bias-correct overall effect size estimate:", round(x = results$trim.es,
                                                            digits = 2),
         tags$br(),
         "NOTE WOULD BE NICE TO HAVE PVAL",
         tags$br(), tags$br(),
         tags$strong("PET"),
         tags$br(),
         "Estimate of bias:", round(x = results$pet.b1,
                                    digits = 2),
         tags$i("p"), "=", round(x = results$pet.b1.p,
                                 digits = 2),
         "Bias-adjusted overall effect size estimate:", round(x = results$pet.int,
                                                              digits = 2),
         tags$i("p"), "=", round(x = results$pet.int.p,
                                 digits = 2),
         tags$br(), tags$br(),
         tags$strong("PEESE"),
         tags$br(),
         "Estimate of bias:", round(x = results$peese.b1,
                                    digits = 2),
         tags$i("p"), "=", round(x = results$peese.b1.p,
                                 digits = 2),
         "Bias-adjusted overall effect size estimate:", round(x = results$peese.int,
                                                              digits = 2)
)
